services:
  frontend:
    build:
      context: ./react-javascript/
      dockerfile: Dockerfile
    expose:
      - "5173"
    networks:
      - piia-platform

networks:
  piia-platform:
    external: true