services:
  frontend:
    build:
      context: ./react-javascript/
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_APP_HOST=${NEXT_PUBLIC_APP_HOST}
    expose:
      - "5173"
    networks:
      - piia-platform

networks:
  piia-platform:
    external: true
